radartype=2;
reportOwnPosition=1;
receiveRemoteTargets=1;
reportRemoteTargets=1;
laserScanner=1;
lockDetectionSystem=4;

incomingMissileDetectionSystem=16;
soundLocked[]=
{
	"\A3\Sounds_F\weapons\Rockets\locked_1",
	1,
	1
};
soundIncommingMissile[]=
{
	"\A3\Sounds_F\vehicles\air\noises\alarm_locked_by_missile_4",
	0.39810717,
	1
};