magazines[]=
{
	"RC_60Rnd_30mm_MP_T_Y",
	"RC_60Rnd_30mm_MP_T_Y",
	"RC_60Rnd_30mm_MP_T_Y",
	"RC_60Rnd_30mm_GPR_T_Y",
	"RC_60Rnd_30mm_GPR_T_Y",
	"Laserbatteries",
	"SmokeLauncherMag",
	"SmokeLauncherMag"
};