class Turrets;
class MainTurret;
class CommanderOptics;
class ViewOptics;
class Components;
class UserActions;
class EventHandlers;
class AnimationSources;
class bashbar;
class rubberskirts;
class camonethull;
class camonetturret;
class TextureSources;
class woodland;
class arid;
class OpticsIn;
class Wide;
class HitPoints;
class HitHull;
class HitLTrack;
class HitRTrack;
scope=0;
scopeCurator=0;