author="Ascent";
scope=2;
role="Crewman";
uniformClass="U_C_WorkerCoveralls";
engineer=1;	//angi
//canDeactivateMines=1;	//angi
//detectSkill=31;	//angi
//cost=93000;
//editorPreview="\A3\EditorPreviews_F\Data\CfgVehicles\B_crew_F.jpg";
/*
class UniformInfo
{
	class SlotsInfo
	{
		class Googles: UniformSlotInfo
		{
			slotType=603;
		};
		class Headgear: UniformSlotInfo
		{
			slotType=605;
		};
	};
};
*/
weapons[]=
{
	"SMG_03C_TR_black",
	"Throw",
	"Put"
};
respawnWeapons[]=
{
	"SMG_03C_TR_black",
	"Throw",
	"Put"
};
magazines[]=
{
	"50Rnd_570x28_SMG_03",
	"50Rnd_570x28_SMG_03",
	"50Rnd_570x28_SMG_03",
	"50Rnd_570x28_SMG_03",
	"50Rnd_570x28_SMG_03",
	"HandGrenade",
	"HandGrenade",
	"SmokeShell",
	"SmokeShell",
	"Chemlight_green",
	"Chemlight_green"
};
respawnMagazines[]=
{
	"50Rnd_570x28_SMG_03",
	"50Rnd_570x28_SMG_03",
	"50Rnd_570x28_SMG_03",
	"50Rnd_570x28_SMG_03",
	"50Rnd_570x28_SMG_03",
	"HandGrenade",
	"HandGrenade",
	"SmokeShell",
	"SmokeShell",
	"Chemlight_green",
	"Chemlight_green"
};
/*
linkedItems[]=
{
	"V_TacVest_oli",
	"H_HelmetCrew_I",
	"G_Tactical_Clear",
	"ItemMap",
	"ItemCompass",
	"ItemWatch",
	"ItemRadio",
	"NVGoggles_OPFOR"
};
respawnLinkedItems[]=
{
	"V_TacVest_oli",
	"H_HelmetCrew_I",
	"G_Tactical_Clear",
	"ItemMap",
	"ItemCompass",
	"ItemWatch",
	"ItemRadio",
	"NVGoggles_OPFOR"
};
*/