class ViewPilot;
class Viewoptics;
class Turrets;
class MainTurret;
class OpticsIn;
class Wide;
class Components;
class HitPoints;
class AnimationSources;
class UserActions;
class EventHandlers;
scope=0;
scopeCurator=0;
