name = "Remote Controlled Artillery"
author = "Ascent, Fluffy"
prefix = "RCA"
mainprefix = "z"


[version]
major = 1 # Overrides path when set
minor = 0
patch = 0
git_hash = 0

[hemtt.launch]
workshop = [
	"450814997", # CBA_A3
]

[hemtt.release]
sign = true
archive = false

[asc]
enabled = false

[files]
include = [
	"RCpic.paa",
	"readme.txt"
]
