class ViewPilot;
class Viewoptics;
class OpticsIn;
class Wide;
class Components;
class FoldArms;
class RotorPark;
class AnimationSources;
//class HitPoints;
class UserActions;
class EventHandlers;
scope=0;
scopeCurator=0;
